### ISSUE TITLE
Not building an .mdimporter plug in

### ISSUE THREAD

**Issue by 101Dude** [MaddTheSane/MKVImport#1]
I am not too familiar with Xcode. This project is failing for me and I really want it to work.

I am getting it to build but I get an error at the end

> Usage: /Users/john/Library/Developer/Xcode/DerivedData/MKVImporter-etgqzrdomlyxgrcipsgtuthujdlm/Build/Products/Debug/OSTypeMapperGenerator outputFile
> Program ended with exit code: 1

I don't have a .mdimport file in the build folder

```
Products
  Debug
    OSTypeMapperGenerator.swiftmodule
      Project
        x86_64-apple-macos.swiftsourceinfo
    x86_64-apple-macos.abi.json
    x86_64-apple-macos.swiftdoc
    x86_64-apple-macos.swiftmodule
  OSTypeMapperGenerator
```

**Comment by MaddTheSane** [comment]
Did you check out the submodules?

**Comment by 101Dude** [comment]
I gave up and downloaded the zip file.

wasn't the Xcode output supposed to be an .mdimporter plug in?

**Comment by MaddTheSane** [comment]
You didn't do `git clone --recurse-submodules https://github.com/MaddTheSane/MKVImport.git`?

**Comment by 101Dude** [comment]
I didn't. I went to Code and Opened with Xcode. I also tried Open with GitHub Desktop... Keep in mind I am a little ignorant :)

**Comment by 101Dude** [comment]
OK I did as you said. I `cd` into my github desktop directory and ran that command. `git clone --recurse-submodules https://github.com/MaddTheSane/MKVImport.git`. Worked! Thank you. I then built using Xcode.

A few deprecations appeared.

```
ebml
/Users/john/GitHub/MKVImport/Vendor/libebml/src/Debug.cpp
/Users/john/GitHub/MKVImport/Vendor/libebml/src/Debug.cpp:133:7 'sprintf' is deprecated: This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead.

/Users/john/GitHub/MKVImport/Vendor/libebml/src/Debug.cpp:138:7 'sprintf' is deprecated: This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead.

/Users/john/GitHub/MKVImport/Vendor/libebml/src/Debug.cpp:145:7 'sprintf' is deprecated: This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead.

/Users/john/GitHub/MKVImport/Vendor/libebml/src/Debug.cpp:147:7 'sprintf' is deprecated: This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead.

/Users/john/GitHub/MKVImport/Vendor/libebml/src/Debug.cpp:150:12 'vsprintf' is deprecated: This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use vsnprintf(3) instead.

MKVImporter
/Users/john/GitHub/MKVImport/Vendor/libmatroska/matroska/KaxBlock.h
/Users/john/GitHub/MKVImport/Vendor/libmatroska/matroska/KaxBlock.h:235:57 Implicit conversion loses integer precision: 'size_type' (aka 'unsigned long') to 'unsigned int'

```

https://forums.developer.apple.com/forums/thread/714675

**Comment by MaddTheSane** [comment]
Those are warnings, not errors.
They are also in the third-party modules/libraries.

**Comment by 101Dude** [comment]
I just want to thank you again for this and for helping me get it straightened out. Hopefully someone else will find it useful.
